site_name: mixturemm

site_url: https://FAIRChemistry.github.io/mixturemm

repo_url: https://github.com/FAIRChemistry/mixturemm

theme:
    palette: 
        - scheme: default
          primary: red
          toggle:
            icon: material/toggle-switch-off-outline 
            name: Switch to dark mode
        - scheme: slate 
          primary: red
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    name: material
    font:
        text: Roboto Slab
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/github
        logo: fontawesome/solid/atom
    features:
        - navigation.instant
        - search.highlight
        - navigation.tabs
        - navigation.top
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          # execute: True
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.highlight:
          linenums: true
    - pymdownx.tabbed:
          alternate_style: true
    - toc:
          permalink: true
    - admonition
    - pymdownx.details
    - meta
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Scientific background: scientific.md
    - Report Issues: https://github.com/FAIRChemistry/mixturemm/issues
    - API Reference:
          - mixturemm module: mixturemm.md
          - background modue: background.md
          - tools module: tools.md
          - utils module: utils.md