name: docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  $CONDA/bin/conda activate base
                  $CONDA/bin/conda install -c conda-forge openmm
                  $CONDA/bin/conda install -c omnia packmol
                  $CONDA/bin/conda install -c conda-forge mdanalysis
                  $CONDA/bin/conda install -c conda-forge mdtraj
                  $CONDA/bin/conda install -c anaconda more-itertools
                  $CONDA/bin/conda install -c conda-forge tidynamics
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
              run: |
                  $CONDA/bin/conda init bash
                  $CONDA/bin/conda activate base
                  python -m pip install --upgrade pip
                  pip install mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
                  mkdocs gh-deploy --force
