name: docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - uses: s-weigand/setup-conda@v1
              with:
                  activate-conda: false
            - name: Install dependencies
              run: |
                  conda activate base
                  conda install -c conda-forge openmm
                  conda install -c omnia packmol
                  conda install -c conda-forge mdanalysis
                  conda install -c conda-forge mdtraj
                  conda install -c anaconda more-itertools
                  conda install -c conda-forge tidynamics
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
                  conda activate base
                  python -m pip install --upgrade pip
                  pip install mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
                  mkdocs gh-deploy --force
